version: "3.9"

services:
    scrypt:
        build:
          context: .
          dockerfile: ./Dockerfile
        container_name: python_scrypt
        restart: unless-stopped
        volumes:
          - .:/app
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_HOST=db
        ports:
          - 8000:8000
        command: python python_scrypt.py
        depends_on:
          - db
    db:
      image: postgres:14-alpine
      container_name: db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432

volumes:
  postgres_data: